create table person
(
    id            int generated by default as identity primary key,
    full_name     varchar(50) not null,
    year_of_birth int         not null
);

create table book
(
    id        int generated by default as identity,
    title     varchar(40) not null,
    author    varchar(30) not null,
    year      int check (year > 1500),
    person_id int,
    foreign key (person_id) references person (id) on delete set null
);
alter table book
    add column taken_at timestamp;

insert into person(full_name, year_of_birth)
values ('Olga Kinga', 2005),
       ('Ghost Mane', 1994),
       ('Oliver Tree', 1940),
       ('Oleg Barysh', 1998);

insert into book(title, author, year, person_id)
VALUES ('Fight for mercy', 'Stephen King', 1999, 2),
       ('Java for beginners', 'John Gosling', 1995, null),
       ('Math', 'Doctor Math', 2005, 2),
       ('Fight club', 'Cool guy', 1999, 3),
       ('Simple love', 'Cool guy', 1988, 4),
       ('Call of duty', 'Ghost', 1999, 2),
       ('Fight club 2', 'Cool guy', 2020, 2);